fieldLayouts:
  6005eaa1-f30a-4edc-b6c3-c9ca398752e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f041b931-96f8-41bf-b19c-c63f77c616ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 013dda90-a7f9-4fd2-9e45-2a2efdb2124a # Customer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 539e29ed-e6ae-4876-a117-a54b1504ecf7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fa3978b-3d45-4707-b9de-269d8999b998 # Book
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6cab6f52-2f19-4565-bb02-1dce10d536be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 389eeb11-ec6e-4644-923b-780ec29f6998 # Borrow Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 125965eb-5897-4758-83a1-aa4001005d71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a67ef876-0f99-4abf-b176-a331c7ae7bd4 # Return Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf8f05ad-6b81-4a08-ac47-37456f3e1d0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c45c223-a1a2-4107-92ac-af50164f3732
        userCondition: null
handle: borrowRecord
hasTitleField: true
name: 'Borrow Record'
section: 5b5a7a58-6be2-491e-a53a-c20a2f84ece2 # Borrow Records
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
