columnSuffix: cctekmqo
contentColumnType: text
fieldGroup: 52a4e04d-d348-4db0-adbd-2115775ca5f2 # Library Fields
handle: isbn
instructions: null
name: ISBN
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
